delete FROM eviveportal.campaign_content WHERE type='WEB' and client_code='1037' and role='DEFAULT' and locale='en_US' and template_id='low_humidity_high_spirits_l7';
delete FROM eviveportal.campaign_content WHERE type='WEB' and client_code='1037' and role='DEFAULT' and locale='en_US' and template_id='low_humidity_high_spirits_l6';
delete FROM eviveportal.campaign_content WHERE type='WEB' and client_code='1037' and role='DEFAULT' and locale='en_US' and template_id='low_humidity_high_spirits_l5';
delete FROM eviveportal.campaign_content WHERE type='WEB' and client_code='1054' and role='DEFAULT' and locale='en_US' and template_id='low_humidity_high_spirits_nl1';

